---
- name: Install OCP
  hosts: haproxy
  vars_files:
    - vars.yml
  gather_facts: true

  tasks:
    - name: Fail the task when ssh public key is not defined
      ansible.builtin.fail:
      when: ssh_pub_key is not defined

    - name: Generate ssh key pair in haproxy
      ansible.builtin.shell: |
        ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y

    - name: Get the public key
      ansible.builtin.set_fact:
        ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Install haproxy
      ansible.builtin.include_tasks:
        file: install-haproxy.yml

    - name: Generate OCP config
      ansible.builtin.include_tasks:
        file: generate-ocp-config.yml

    - name: Print the url for node installation
      ansible.builtin.debug:
        msg: "coreos-installer install /dev/sda --insecure-ignition \
          --ignition-url=http://{{ haproxy_ip }}:8080/ocp/bootstrap.ign \
          --copy-network"

    - name: Check all fqdn for OCP
      ansible.builtin.include_tasks:
        file: check_fqdn.yml
      loop: "{{ apis }}"

    - name: Check ip address of nodes
      ansible.builtin.include_tasks:
        file: check_node_ip.yml
      loop:
        - "{{ masters | dict2items }}"
        - "{{ workers | dict2items }}"
        - "{{ bootstrap | dict2items }}"
