apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx2
  name: nginx2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx2
    spec:
      initContainers:
      - image: quay.io/official-images/bash
        name: initc
        command:
        - sh
        - "-c"
        - |
          echo "aaaaaaa bbbbbbbbbbbb ccccccccccc" > /work-dir/index.html
        volumeMounts:
        - name: www
          mountPath: "work-dir"
      containers:
      - image: quay.io/telco5gci/nginx
        name: nginx2
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        resources: {}
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: task-pv-claim
status: {}
