---
- hosts: all
  tasks:
    - name: install chrony
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"
    - name: install chrony 2
      apt:
        name: chrony
        state: present
      when: ansible_distribution == "Ubuntu"
