---
- hosts: nodes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start httpd
      service:
        name: httpd
        enabled: yes
        state: started
    - name: apply FW rules
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

