---

- hosts: localhost
  tasks:
  - name: "Set fact on localhost"
    set_fact:
      my_test_fact: "Hello"

  - name: "Copy fact to other servers"
    set_fact:
      my_test_fact: "{{ my_test_fact }}"
    delegate_to: "{{ item }}"
    delegate_facts: True
    with_items: "{{ groups['all'] }}"
    when: item != "localhost"

- hosts: nodes
  gather_facts: True
  tasks:
  - name: "Show fact on server1"
    debug: var=my_test_fact
