---
- name: mariadb server installation
  hosts: localhost
  vars_files:
    - db/db_vars.yml
  tasks:
    - name: install db packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ db.packages }}"

    - name: start db
      service:
        name: "{{ db.service }}"
        state: started
        enabled: true

    - name: create db user
      mysql_user:
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
        host: 'localhost'
        name: admin
        password: password
        priv: "*.*:ALL,GRANT"

    - name: create db
      mysql_db:
        name: "test_1234"
        login_user: admin
        login_password: password
        state: present
