---
- hosts: localhost
  vars_files:
    - vars.yml
  gather_facts: True

  tasks:
    - fail:
        msg: "Memeory should be > 2GB"
      when: ansible_memtotal_mb | int < 2000
        
    - name: Install dnsmasq
      yum:
        name: dnsmasq
        state: latest

    - name: Backup original dnsmasq conf
      copy:
        src: /etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf.orig
        remote_src: true

    - name: Remove old config file
      file:
        path: /etc/dnsmasq.conf
        state: absent

    - name: Create new content in dnsmasq.conf
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface={{ net_int }}
          bind-interfaces
          domain=linuxhint.local
          dhcp-range={{ net_int }},{{ dhcp_start }},{{ dhcp_end }},{{ netmask }},8h
          dhcp-option=option:router,{{ int_gateway }}
          dhcp-option=option:dns-server,{{ int_gateway }}
          dhcp-option=option:dns-server,8.8.8.8
          enable-tftp
          tftp-root=/netboot/tftp
          dhcp-boot=pxelinux.0,linuxhint-s80,{{ int_gateway }}
          pxe-prompt="Press F8 for PXE Network boot.",5
          pxe-service=x86PC,"Install OS via PXE",pxelinux

    - name: Create /netboot folder and restart service
      shell: |
        mkdir -pv /netboot/tftp/pxelinux.cfg
        systemctl restart dnsmasq
        systemctl enable dnsmasq

    - name: Install PXE bootloader files
      yum:
        name: syslinux
        state: latest

    - name: Copy files to tftp folder
      copy:
        src: "/usr/share/syslinux/{{ item }}"
        dest: /netboot/tftp/
      loop:
        - pxelinux.0
        - menu.c32
        - ldlinux.c32
        - libutil.c32
        - memdisk

