apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: mysql-pv
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /lv2
    server: 10.1.4.119
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

