---
- hosts: clients
  vars_files:
    - vars.yml

  tasks:
  - name: check OS version
    fail:
    when: 
    - ansible_distribution_major_version != '8'
    - ansible_distribution_major_version != '9'

  - name: Install the necessary packages for LDAP client setup
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - openldap-clients 
      - sssd 
      - sssd-ldap 
      - oddjob-mkhomedir 
      - openssl-perl

  - name: Add sssd.conf
    template:
      src: client/sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      mode: 0600
      owner: root
      group: root

  - name: Copy template to ldap.conf
    template:
      src: client/ldap.conf.j2
      dest: /etc/openldap/ldap.conf

  - name: Run commands
    shell: |
      authselect select sssd with-mkhomedir --force
      systemctl enable sssd.service --now
      systemctl enable oddjobd.service --now
  