---
- hosts: host
  vars:
    disk_map: []

  tasks:
    - include_tasks: checknewdisks.yml

    - include_tasks: partition.yml
      loop: "{{ new_dev }}"
      
    - name: Update devices into /dev/sdx1
      set_fact:
        new_dev: "{{ new_dev | map('regex_replace', '$', '1') | list }}"

    - name: Extend volume group
      shell: |
        vgextend {{ vgname }} {{ new_dev | join(' ') }}

    - include_tasks: get_lvs.yml

    - name: Mirror the LV
      shell: |
        lvconvert -y -m 1 /dev/{{ vgname }}/{{ item }} {{ new_dev | join(' ') }}
      loop: "{{ lvs.stdout_lines }}"

    - name: Generate lvs report
      shell: |
        lvs {{ vgname }} --reportformat json
      register: report

    - name: Convert from json
      set_fact:
        jsondata: "{{ report.stdout | from_json }}"

    - debug:
        msg: "{{ item.lv_name }} => {{ item.copy_percent }}"
      loop: "{{  jsondata.report[0].lv }}"

