---
- hosts: host
  vars:
    old_dev: []

  tasks:
    - name: Read the old disks from file
      command: "cat /var/tmp/old-disk"
      register: disk

    - set_fact:
        old_disks: "{{ disk.stdout_lines | join(' ') }}"

    - include_tasks: get_lvs.yml

    - debug:
        msg: "{{ lvs }}"

    # - shell: |
    #     lvconvert -y -m 0 /dev/{{ vgname }}/{{ item }} {{ old_disks }}
    #   loop: "{{ lvs.stdout_lines }}"

    # - shell: |
    #     vgreduce {{ vgname }} {{ old_disks }}

