---
# tasks file for roles/linux
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Check the high risk packages
  assert:
    that:
      - ansible_facts.packages[item]  is undefined
  loop: "{{ lnx_pkg_list[ansible_os_family] }}"

- name: Check PermitRoot in /etc/ssh/sshd_config
  shell: |
    egrep -i '^PermitRootLogin\s+yes' {{ sshd_config }}

- name: Check file permissions
  stat:
    path: "{{ item.name }}"
  register: st
  loop: "{{ files }}"

- name: Check content
  debug:
    msg: "{{ st }}"
