apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-pv1
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /lv1
    server: 10.1.4.119
