---
- hosts: flask
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present

    - name: start apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: install mod_wsgi
      yum:
        name: python3-mod_wsgi
        state: present

    - name: create python virtual env
      shell: |
        cd /var/www/html
        mkdir flask
        python -m venv venv
        source venv/bin/activate
        pip install flask

    - name: copy template
      template:
        src: wsgi.j2
        dest: /var/www/html/flask/flask-app.wsgi
        owner: apache
        group: apache

    - name: copy template
      template:
        src: app.py.j2
        dest: /var/www/html/flask/app.py
        owner: apache
        group: apache

    - name: copy test files
      copy:
        src: test
        dest: /var/www/html/flask
        owner: apache
        group: apache

    - name: copy apache config
      copy:
        src: "flask.conf"
        dest: "/etc/httpd/conf.d/flask.conf"
        owner: root
        group: root
        mode: '0644'

    - name: restart httpd
      service:
        name: httpd
        state: restarted
