---
# defaults file for roles/linux
lnx_pkg_list: 
  "RedHat":
    - "xinetd"
    - "ypserv"
    - "telnet-server"
    - "tftp-server"
    - "rsh-server"
  "Debian":
    - "nis"
    - "xinetd" 
    - "yp-tools" 
    - "tftpd"
    - "atftpd"
    - "tftpd-hpa"
    - "telnetd" 
    - "rsh-server" 
    - "rsh-redone-server"
    - "openssh-server"

sshd_config: "/etc/ssh/sshd_config"

files:
  - {name: "/etc/shadow", perm: "1111"}
  - {name: "/etc/passwd", perm: "0644"}
