#---
## tasks file for setup-k8s
#- include_tasks: yum_update.yml
# - fail:
#     msg: "hostname cannot be used in the playbook"
#   any_errors_fatal: true
#   when:
#     - ansible_hostname is not match(".*master[0-9]")
#     - ansible_hostname is not match(".*worker[0-9]")

- include_tasks: add_config.yml

- include_tasks: setup_containerd.yml

- include_tasks: disable_fw.yml # rebooting vm in disable_fw.yml

- include_tasks: install_k8s.yml

- name: kubeadm init the cluster
  include_tasks: init_k8s.yml
  # when: ansible_hostname is match(".*master1")
  when: inventory_hostname == groups['masters'][0]

- name: run join command in clients
  # command: "{{ xxxx['content']|b64decode }}"
  command: "{{ hostvars[groups['masters'][0]]['client_join_cmd'].stdout }}"
  # when: ansible_hostname is match(".*worker[0-9]")
  when:  inventory_hostname in groups['workers']

- name: master generate new certificate key
  shell: |
     kubeadm init phase upload-certs --upload-certs 2>/dev/null | tail -1
  register: cert_key
  when: inventory_hostname == groups['masters'][0]

- name: run join command in other masters
  command: "{{ hostvars[groups['masters'][0]]['client_join_cmd'].stdout }}  --control-plane --certificate-key {{ hostvars[groups['masters'][0]]['cert_key'].stdout }}"
  # when: ansible_hostname is match(".*master[2-9]")
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]
