/* Requires the Docker Pipeline plugin */
pipeline {
    agent { docker { 
	image 'python:3.12.0-alpine3.18'
//	args '-u root --privileged' */
	label 'docker'
	 } 
	}
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh "ls -lat"
            }
        }
        stage('Build') {
            steps {
		sh """
			python -m venv venv
          		source venv/bin/activate
          		pip install redis
		  """
            }
        }

    }
}
