/* Requires the Docker Pipeline plugin */
pipeline {
    agent { 
        docker { 
            image 'python:3.12.0-alpine3.18'
            label 'docker'
        } 
    }
    stages {
        stage("Clone sources") {
            // agent { 
            //     docker { 
            //         image 'python:3.12.0-alpine3.18'
            //         label 'docker'
            //     } 
            // }
            steps {
                checkout scm
            }
        }
        stage('Build') {
            // agent { 
            //     docker { 
            //         image 'python:3.12.0-alpine3.18'
            //         //args '-u root --privileged' */
            //         label 'docker'
            //         //customWorkspace  '/var/tmp/jenkins'
            //     } 
            // }            
            steps {
                sh """
                pip install -r requirements.txt
                """
                // sh "ls -lt"
                // sh '''
                //     python -m venv venv
                //     source venv/bin/activate
                //     pip install -r requirements.txt
                //     pytest tests
                // '''
            }
        }
        stage('Test') {
            steps {
                sh """
                pytest tests
                """
            }
        }
        // stage('Test2') {
        //     agent {
        //         node {
        //             label 'docker'
        //         }
        //     }
        //     steps {
        //         sh """
        //             docker build -t xxx .
        //         """
        //     }
        // }

    }
}
