apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        volumeMounts:
          - name: pvc1
            mountPath: /usr/share/nginx/html
      volumes:
        - name: pvc1
          persistentVolumeClaim:
            claimName: nfs-pvc1
        
status: {}
