apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: build-observer
  name: build-observer
spec:
  serviceAccountName: build-bot
  containers:
  - image: alpine
    name: build-observer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
