---
- hosts: promoted-master
  tasks:
    - name: Check the named in all hosts
      shell: "ps -ef | grep named | grep -v grep"

    - name: Backup the named.conf
      copy:
        src: /etc/named.conf
        dest: "/var/tmp/named.conf.{{ ansible_date_time.iso8601_basic_short }}"
        remote_src: yes
        validate: /usr/sbin/named-checkconf %s

    - name: xxxx
      lineinfile:
        path: /etc/named.conf
        regexp: 'type\s+slave'
        state: absent