---
- hosts: promotedmaster
  tasks:
    - name: Check the named in all hosts
      shell: "ps -ef | grep named | grep -v grep"

    - name: Copy /etc/named.conf
      copy:
        src: /etc/named.conf
        dest: /etc/named.conf.slave.{{ ansible_date_time.iso8601_basic_short }}
        remote_src: true

    - name: Copy /etc/named.conf
      copy:
        src: /var/named/data/
        dest: /var/tmp/
        remote_src: true

