---
- hosts: promotedmaster
  tasks:
    - name: Check the named in all hosts
      shell: "ps -ef | grep named | grep -v grep"

    - name: Copy /etc/named.conf
      copy:
        src: /etc/named.conf
        dest: "{{ item }}"
        remote_src: true
      loop:
        - "/etc/named.conf.slave.{{ ansible_date_time.iso8601_basic_short }}"
        - /etc/named.conf.promote-master

    - name: Copy /etc/named.conf
      shell: |
        alias cp=cp
        cd /var/named
        mkdir standby
        cp -pfr data/* standby/

    - name: Replace type to master
      replace:
        path:  /etc/named.conf.promote-master
        regexp: '(^\s+type\s+)slave(.*)'
        replace: '\1master\2'

    - name: Replace data folder to standby
      replace:
        path:  /etc/named.conf.promote-master
        regexp: '(\s+file\s")data(.*)'
        replace: '\1standby\2'

    - name: 
      replace:
        path: /etc/named.conf.promote-master
        regexp: '^\s+masters\_.};'
        replace: ''
        validate: /usr/sbin/named-checkconf %s

